#!/usr/bin/env bash
# Generate the SHA-512 signature fixtures for tests/test_sha512_sigs.mojo.
#
# With OpenSSL (>= 3.4) in a temporary directory, writes
# tests/sha512_fixtures.mojo:
#   - CA + leaf chains signed with SHA-512: sha512WithRSAEncryption,
#     RSASSA-PSS (SHA-512), ecdsa-with-SHA512 on P-256 and on P-384
#     (RSA keys are 2048-bit);
#   - SHA-512 signatures over MSG made with the four leaf keys: PKCS#1 v1.5,
#     PSS (MGF1-SHA-512, salt 64), ECDSA P-256 and P-384.
# Each chain is checked with `openssl verify` before it is written out.
# Private keys stay in the temporary directory and are deleted.
#
# Usage (from the repo root): bash tests/gen_sha512_fixtures.sh
set -euo pipefail

OUT="$(cd "$(dirname "$0")" && pwd)/sha512_fixtures.mojo"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
cd "$WORK"

START="20250101000000Z"
END="21250101000000Z"
MSG="tls 1.6.1 sha-512 signature fixture"
printf '%s' "$MSG" > msg.bin

hexof() { xxd -p "$1" | tr -d '\n'; }
der() { openssl x509 -in "$1" -outform DER -out "$1.der"; hexof "$1.der"; }

rsa_key() { openssl genrsa -out "$1.key" 2048 2>/dev/null; }
ec_key() { openssl ecparam -name "$2" -genkey -noout -out "$1.key" 2>/dev/null; }

# chain <prefix> <sigopts...>: self-signed CA and a leaf, both signed with them
CA_EXT='basicConstraints=critical,CA:TRUE\nkeyUsage=critical,keyCertSign\n'
chain() {
    local p="$1"; shift
    printf '%b' "$CA_EXT" > ca.ext
    printf 'basicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature\nextendedKeyUsage=serverAuth\nsubjectAltName=DNS:%s.example\n' "$p" > leaf.ext
    openssl req -new -key "${p}_ca.key" -subj "/CN=SHA-512 $p CA" -out ca.csr
    openssl x509 -req -in ca.csr -key "${p}_ca.key" -out "${p}_ca.pem" "$@" \
        -not_before "$START" -not_after "$END" -extfile ca.ext 2>/dev/null
    openssl req -new -key "${p}_leaf.key" -subj "/CN=$p.example" -out leaf.csr
    openssl x509 -req -in leaf.csr -CA "${p}_ca.pem" -CAkey "${p}_ca.key" -CAcreateserial \
        -out "${p}_leaf.pem" "$@" -not_before "$START" -not_after "$END" -extfile leaf.ext 2>/dev/null
    openssl verify -CAfile "${p}_ca.pem" "${p}_leaf.pem" >/dev/null
}

# ── Chains ───────────────────────────────────────────────────────────────────
rsa_key rsa_ca; rsa_key rsa_leaf
chain rsa -sha512
rsa_key pss_ca; rsa_key pss_leaf
chain pss -sha512 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:64 -sigopt rsa_mgf1_md:sha512
ec_key ec256_ca prime256v1; ec_key ec256_leaf prime256v1
chain ec256 -sha512
ec_key ec384_ca secp384r1; ec_key ec384_leaf secp384r1
chain ec384 -sha512

# ── Raw signatures over MSG, made with the leaf keys above ───────────────────
openssl dgst -sha512 -sign rsa_leaf.key -out rsa_pkcs1.sig msg.bin
openssl dgst -sha512 -sign pss_leaf.key -sigopt rsa_padding_mode:pss \
    -sigopt rsa_pss_saltlen:64 -sigopt rsa_mgf1_md:sha512 -out rsa_pss.sig msg.bin
openssl dgst -sha512 -verify <(openssl x509 -in pss_leaf.pem -pubkey -noout) \
    -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:64 -signature rsa_pss.sig msg.bin >/dev/null
openssl dgst -sha512 -sign ec256_leaf.key -out p256.sig msg.bin
openssl dgst -sha512 -sign ec384_leaf.key -out p384.sig msg.bin

{
    echo "# Generated by tests/gen_sha512_fixtures.sh - do not edit."
    echo "# SHA-512 signatures (raw and in certificate chains) made by $(openssl version | cut -d' ' -f1-2)."
    echo
    echo "comptime MSG = \"$MSG\""
    echo
    echo "# Signatures over MSG by the leaf keys below: RSA_LEAF (PKCS#1 v1.5),"
    echo "# PSS_LEAF (PSS, MGF1-SHA-512, salt 64), EC256_LEAF and EC384_LEAF (DER ECDSA)"
    echo "comptime RSA_PKCS1_SIG = \"$(hexof rsa_pkcs1.sig)\""
    echo "comptime RSA_PSS_SIG = \"$(hexof rsa_pss.sig)\""
    echo "comptime P256_SIG = \"$(hexof p256.sig)\""
    echo "comptime P384_SIG = \"$(hexof p384.sig)\""
    echo
    echo "# Chains (self-signed CA, leaf with SAN <name>.example), all signed with SHA-512"
    for p in rsa pss ec256 ec384; do
        P="$(echo "$p" | tr 'a-z' 'A-Z')"
        echo "comptime ${P}_CA = \"$(der ${p}_ca.pem)\""
        echo "comptime ${P}_LEAF = \"$(der ${p}_leaf.pem)\""
    done
} > "$OUT"
echo "wrote $OUT"
