# ============================================================================
# test_cert_path.mojo — certificate path validation (RFC 5280 constraints)
# ============================================================================
# Fixtures: tests/path_fixtures.mojo, generated by tests/gen_path_fixtures.sh
# (ECDSA P-256 PKI, valid until 2125). Each case was checked against
# `openssl verify -purpose sslserver`; the two intentional differences are
# noted on their tests.
# ============================================================================

from crypto.cert import X509Cert, cert_parse, cert_chain_verify, _parse_asn1_time
from path_fixtures import (
    ROOT, INTER, LEAF_OK, EVIL, BANK, INTER_NOBC, LEAF_NOBC, INTER_KU, LEAF_KU,
    INTER_PL0, SUB_PL0, LEAF_PL0_DEEP, LEAF_PL0, LEAF_CLIENT, LEAF_NOEKU,
    LEAF_KENC, INTER_CRIT, LEAF_CRIT, INTER_NONCRIT, LEAF_NONCRIT, INTER_NC,
    LEAF_NC, LEAF_DN, LEAF_EXPIRED, INTER_FUTURE, LEAF_FUTURE, NEW_ROOT,
    CROSS_EXPIRED, INTER_X, LEAF_X, STRAY_INTER, STRAY_LEAF,
    INTER_NCD, LEAF_NCD_OK, LEAF_NCD_BAD, INTER_NCX, LEAF_NCX_OK, LEAF_NCX_BAD,
    LEAF_NCX_WILD, INTER_NCIP, LEAF_NCIP_OK, LEAF_NCIP_BAD, INTER_NCEMAIL,
    LEAF_NCEMAIL, INTER_EKU_EMAIL, LEAF_EKU_EMAIL, INTER_EKU_SERVER,
    LEAF_EKU_SERVER, RSA1024_LEAF, RSA2048_LEAF, LEAF_IPSAN, LEAF_DNS_IP,
)


def run_test[test_fn: def() thin raises -> None](
    name: String,
    mut passed: Int,
    mut failed: Int,
):
    try:
        test_fn()
        print("  PASS:", name)
        passed += 1
    except e:
        print("  FAIL:", name, "-", String(e))
        failed += 1


def hex_to_bytes(h: String) -> List[UInt8]:
    var raw = h.as_bytes()
    var n = len(raw) // 2
    var out = List[UInt8](capacity=n)
    for i in range(n):
        var hi = raw[i * 2]
        var lo = raw[i * 2 + 1]
        var h_val: UInt8 = (hi - 48) if hi <= 57 else (hi - 87)
        var l_val: UInt8 = (lo - 48) if lo <= 57 else (lo - 87)
        out.append((h_val << 4) | l_val)
    return out^


def cert(h: String) raises -> X509Cert:
    return cert_parse(hex_to_bytes(h))


def chain_of(*hexes: String) raises -> List[X509Cert]:
    var out = List[X509Cert]()
    for i in range(len(hexes)):
        out.append(cert(hexes[i]))
    return out^


def anchors_of(*hexes: String) raises -> List[X509Cert]:
    var out = List[X509Cert]()
    for i in range(len(hexes)):
        out.append(cert(hexes[i]))
    return out^


def expect_ok(chain: List[X509Cert], anchors: List[X509Cert], host: String) raises:
    cert_chain_verify(chain, anchors, host)


def expect_reject(
    chain: List[X509Cert], anchors: List[X509Cert], host: String, why: String
) raises:
    """Require rejection; `why` must appear in the error message."""
    var message = String()
    try:
        cert_chain_verify(chain, anchors, host)
    except e:
        message = String(e)
    if message.byte_length() == 0:
        raise Error("accepted, expected rejection (" + why + ")")
    if message.find(why) < 0:
        raise Error("rejected for the wrong reason: '" + message + "' (expected '" + why + "')")


# ── Accepted paths ──────────────────────────────────────────────────────────

def test_valid_chain() raises:
    expect_ok(chain_of(LEAF_OK, INTER), anchors_of(ROOT), "ok.example")


def test_valid_chain_with_root_included() raises:
    expect_ok(chain_of(LEAF_OK, INTER, ROOT), anchors_of(ROOT), "ok.example")


def test_pathlen_zero_direct_leaf() raises:
    expect_ok(chain_of(LEAF_PL0, INTER_PL0), anchors_of(ROOT), "direct.example")


def test_leaf_without_eku() raises:
    expect_ok(chain_of(LEAF_NOEKU, INTER), anchors_of(ROOT), "noeku.example")


def test_unknown_noncritical_extension() raises:
    expect_ok(chain_of(LEAF_NONCRIT, INTER_NONCRIT), anchors_of(ROOT), "noncrit.example")


def test_expired_cross_sign_above_anchor() raises:
    # new_root is trusted; the server also sends an expired cross-signed
    # copy of new_root's key. The path ends at the trusted key, so the
    # expired certificate above it must not matter (DST Root X3, 2021).
    expect_ok(
        chain_of(LEAF_X, INTER_X, CROSS_EXPIRED), anchors_of(NEW_ROOT), "cross.example"
    )


# ── Rejected paths ──────────────────────────────────────────────────────────

def test_exploit_leaf_used_as_ca() raises:
    # The deep-dive exploit: evil.example's CA:FALSE leaf key signs a
    # certificate for bank.example. Accepted by tls 1.4.2.
    expect_reject(
        chain_of(BANK, EVIL, INTER), anchors_of(ROOT), "bank.example", "not a CA"
    )


def test_issuer_without_basic_constraints() raises:
    expect_reject(
        chain_of(LEAF_NOBC, INTER_NOBC), anchors_of(ROOT), "nobc.example", "not a CA"
    )


def test_issuer_key_usage_without_cert_sign() raises:
    expect_reject(
        chain_of(LEAF_KU, INTER_KU), anchors_of(ROOT), "ku.example", "keyCertSign"
    )


def test_path_length_exceeded() raises:
    expect_reject(
        chain_of(LEAF_PL0_DEEP, SUB_PL0, INTER_PL0),
        anchors_of(ROOT),
        "deep.example",
        "path length",
    )


def test_leaf_eku_client_auth_only() raises:
    expect_reject(
        chain_of(LEAF_CLIENT, INTER), anchors_of(ROOT), "client.example", "serverAuth"
    )


def test_leaf_key_usage_without_digital_signature() raises:
    # OpenSSL's generic sslserver purpose also allows keyEncipherment (RSA
    # key exchange). This client only does ECDHE, where the server key must
    # sign (RFC 8446 §4.4.2.2), so digitalSignature is required.
    expect_reject(
        chain_of(LEAF_KENC, INTER), anchors_of(ROOT), "kenc.example", "digitalSignature"
    )


def test_unknown_critical_extension() raises:
    expect_reject(
        chain_of(LEAF_CRIT, INTER_CRIT), anchors_of(ROOT), "crit.example", "critical extension"
    )


def test_critical_name_constraints_enforced() raises:
    # Critical nameConstraints permitting nc.example; the leaf is nc.example.
    # (tls <= 1.5.0 rejected every critical nameConstraints.)
    expect_ok(chain_of(LEAF_NC, INTER_NC), anchors_of(ROOT), "nc.example")


# ── Name constraints, EKU on intermediates, RSA size, IP SANs (1.6.0).
#    Expected results match `openssl verify -purpose sslserver` except where
#    noted. ───────────────────────────────────────────────────────────────

def test_noncritical_name_constraints_permitted() raises:
    # tls 1.5.0 ignored non-critical nameConstraints and accepted the bad leaf
    expect_ok(chain_of(LEAF_NCD_OK, INTER_NCD), anchors_of(ROOT), "www.allowed.example")
    expect_reject(chain_of(LEAF_NCD_BAD, INTER_NCD), anchors_of(ROOT), "victim.example", "name constraint")


def test_excluded_name_constraints() raises:
    expect_ok(chain_of(LEAF_NCX_OK, INTER_NCX), anchors_of(ROOT), "good.example")
    expect_reject(chain_of(LEAF_NCX_BAD, INTER_NCX), anchors_of(ROOT), "x.bad.example", "name constraint")
    # a wildcard that would cover excluded names is rejected too
    expect_reject(chain_of(LEAF_NCX_WILD, INTER_NCX), anchors_of(ROOT), "a.bad.example", "name constraint")


def test_ip_name_constraints() raises:
    expect_ok(chain_of(LEAF_NCIP_OK, INTER_NCIP), anchors_of(ROOT), "10.1.2.3")
    expect_reject(chain_of(LEAF_NCIP_BAD, INTER_NCIP), anchors_of(ROOT), "192.168.1.1", "name constraint")


def test_unsupported_name_constraint_form() raises:
    # rfc822Name constraints are not evaluated, so the chain is rejected
    # (fail closed). OpenSSL evaluates them and accepts (the leaf has no
    # email names): an intentional difference.
    expect_reject(chain_of(LEAF_NCEMAIL, INTER_NCEMAIL), anchors_of(ROOT), "mail.example", "unsupported name constraint")


def test_intermediate_eku() raises:
    # tls 1.5.0 checked extendedKeyUsage on the leaf only
    expect_reject(chain_of(LEAF_EKU_EMAIL, INTER_EKU_EMAIL), anchors_of(ROOT), "ekuemail.example", "extendedKeyUsage")
    expect_ok(chain_of(LEAF_EKU_SERVER, INTER_EKU_SERVER), anchors_of(ROOT), "ekuserver.example")


def test_rsa_minimum_key_size() raises:
    # 2048-bit minimum (CA/Browser Forum). OpenSSL's default security
    # level accepts 1024; its level 2 rejects it, as here.
    expect_reject(chain_of(RSA1024_LEAF, INTER), anchors_of(ROOT), "rsa1024.example", "RSA key")
    expect_ok(chain_of(RSA2048_LEAF, INTER), anchors_of(ROOT), "rsa2048.example")


def test_ip_san_matching() raises:
    expect_ok(chain_of(LEAF_IPSAN, INTER), anchors_of(ROOT), "192.0.2.7")
    expect_ok(chain_of(LEAF_IPSAN, INTER), anchors_of(ROOT), "2001:db8::7")
    expect_ok(chain_of(LEAF_IPSAN, INTER), anchors_of(ROOT), "ipsan.example")
    expect_reject(chain_of(LEAF_IPSAN, INTER), anchors_of(ROOT), "192.0.2.9", "does not match")
    # an IP address is never matched against a dNSName (tls 1.5.0 did)
    expect_reject(chain_of(LEAF_DNS_IP, INTER), anchors_of(ROOT), "192.0.2.8", "does not match")


def test_issuer_subject_mismatch() raises:
    # leaf_dn's signature verifies under inter's key, but it names another
    # issuer.
    expect_reject(
        chain_of(LEAF_DN, INTER), anchors_of(ROOT), "dn.example", "issuer"
    )


def test_expired_leaf() raises:
    expect_reject(
        chain_of(LEAF_EXPIRED, INTER), anchors_of(ROOT), "expired.example", "expired"
    )


def test_not_yet_valid_intermediate() raises:
    expect_reject(
        chain_of(LEAF_FUTURE, INTER_FUTURE), anchors_of(ROOT), "future.example", "not yet valid"
    )


def test_unanchored_chain_decided_before_signatures() raises:
    # The chain does not lead to a trust anchor, and its bottom link is
    # also broken (leaf from one hierarchy, "issuer" from another). The
    # verdict must be "not trusted": signatures are only checked once the
    # path is anchored, so attacker keys never reach the bigint code.
    expect_reject(
        chain_of(LEAF_OK, STRAY_INTER), anchors_of(ROOT), "ok.example", "not trusted"
    )
    expect_reject(
        chain_of(STRAY_LEAF, STRAY_INTER), anchors_of(ROOT), "stray.example", "not trusted"
    )


def test_chain_too_long() raises:
    var chain = List[X509Cert]()
    for _ in range(11):
        chain.append(cert(LEAF_OK))
    expect_reject(chain, anchors_of(ROOT), "ok.example", "too long")


def test_malformed_times_fail_closed() raises:
    var bad = List[String]()
    bad.append("2501010000Z")        # too short
    bad.append("25010100000000Z")    # wrong length for UTCTime
    bad.append("250101000000+")      # no trailing Z
    bad.append("2501a1000000Z")      # non-digit
    bad.append("251301000000Z")      # month 13
    for i in range(len(bad)):
        var b = bad[i].as_bytes()
        var content = List[UInt8]()
        for j in range(len(b)):
            content.append(b[j])
        var raised = False
        try:
            _ = _parse_asn1_time(content, False)
        except:
            raised = True
        if not raised:
            raise Error("accepted malformed UTCTime '" + bad[i] + "'")
    var ok = String("250101000000Z").as_bytes()
    var good = List[UInt8]()
    for j in range(len(ok)):
        good.append(ok[j])
    if _parse_asn1_time(good, False) != 1735689600:
        raise Error("250101000000Z should be 1735689600")


def main() raises:
    var passed = 0
    var failed = 0

    print("=== Certificate Path Validation Tests ===")
    print()

    run_test[test_valid_chain]("valid root → intermediate → leaf", passed, failed)
    run_test[test_valid_chain_with_root_included]("valid chain including the root", passed, failed)
    run_test[test_pathlen_zero_direct_leaf]("pathLen 0 CA issuing a leaf", passed, failed)
    run_test[test_leaf_without_eku]("leaf without EKU", passed, failed)
    run_test[test_unknown_noncritical_extension]("unknown non-critical extension", passed, failed)
    run_test[test_expired_cross_sign_above_anchor]("expired cross-sign above the anchor", passed, failed)
    run_test[test_exploit_leaf_used_as_ca]("EXPLOIT: CA:FALSE leaf used as issuer", passed, failed)
    run_test[test_issuer_without_basic_constraints]("issuer without basicConstraints", passed, failed)
    run_test[test_issuer_key_usage_without_cert_sign]("issuer keyUsage without keyCertSign", passed, failed)
    run_test[test_path_length_exceeded]("pathLenConstraint exceeded", passed, failed)
    run_test[test_leaf_eku_client_auth_only]("leaf EKU clientAuth only", passed, failed)
    run_test[test_leaf_key_usage_without_digital_signature]("leaf keyUsage without digitalSignature", passed, failed)
    run_test[test_unknown_critical_extension]("unknown critical extension", passed, failed)
    run_test[test_critical_name_constraints_enforced]("critical nameConstraints enforced (permitted)", passed, failed)
    run_test[test_noncritical_name_constraints_permitted]("non-critical nameConstraints enforced", passed, failed)
    run_test[test_excluded_name_constraints]("excluded DNS subtrees (incl. wildcards)", passed, failed)
    run_test[test_ip_name_constraints]("IP address name constraints", passed, failed)
    run_test[test_unsupported_name_constraint_form]("unsupported constraint form fails closed", passed, failed)
    run_test[test_intermediate_eku]("extendedKeyUsage enforced on intermediates", passed, failed)
    run_test[test_rsa_minimum_key_size]("RSA keys below 2048 bits rejected", passed, failed)
    run_test[test_ip_san_matching]("IP hosts match iPAddress SANs only", passed, failed)
    run_test[test_issuer_subject_mismatch]("issuer/subject name mismatch", passed, failed)
    run_test[test_expired_leaf]("expired leaf", passed, failed)
    run_test[test_not_yet_valid_intermediate]("not-yet-valid intermediate", passed, failed)
    run_test[test_unanchored_chain_decided_before_signatures]("unanchored chain: not trusted, before signatures", passed, failed)
    run_test[test_chain_too_long]("chain longer than 10", passed, failed)
    run_test[test_malformed_times_fail_closed]("malformed validity times fail closed", passed, failed)

    print()
    print("Results:", passed, "passed,", failed, "failed")
    if failed > 0:
        raise Error(String(failed) + " test(s) failed")
